# Generated by Django 5.0.3 on 2024-04-03 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=datetime.datetime(2024, 4, 3, 16, 56, 28, 634167, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
