# Generated by Django 5.0.3 on 2024-04-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_post_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
